# Generated by Django 5.1.6 on 2025-02-20 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user_type', models.CharField(default='', max_length=30)),
                ('time_slot_from', models.IntegerField(default='')),
                ('time_slot_to', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
