# Generated by Django 5.1.6 on 2025-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_userdetails_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
